#!/bin/bash

PARSER="$HOME/proj-dvs/project-sdk/parser"
Z3="$HOME/proj-dvs/project-sdk/z3-4.3.2"

export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:$PARSER:$Z3/lib
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PARSER:$Z3/lib

./smt $*
