#!/bin/bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
Z3DIR="$HOME/z3-4.3.2"
PARSERDIR="$DIR/parser"

export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:$PARSERDIR:$Z3DIR/lib
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PARSERDIR:$Z3DIR/lib

./smt $*
